import type { Metadata } from "next";
import { Lexend_Deca, Space_Mono } from "next/font/google";

import Header from "@/components/Header";

import "./globals.css";

const spaceMono = Space_Mono({
  variable: "--font-space-mono",
  subsets: ["latin"],
  display: "swap",
  weight: ["700"],
});

const lexendDeca = Lexend_Deca({
  variable: "--font-lexend-deca",
  subsets: ["latin"],
  display: "swap",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Scoot App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${lexendDeca.variable} ${spaceMono.variable} mx-auto max-w-7xl antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
